{lib, ...}:
with lib;
{
  imports = [
    ./ark.nix
    ./bleachbit.nix
    ./blueman.nix
    ./calibre.nix
    ./czkawka.nix
    ./diffuse.nix
    ./drawio.nix
    ./dunst.nix
    ./eog.nix
    ./ferdium.nix
    ./file-roller.nix
    ./firefox.nix
    ./flameshot.nix
    ./geeqie.nix
    ./gnomeencfsmanager.nix
    ./gnomesystemmonitor.nix
    ./gparted.nix
    ./greenclip.nix
    ./hyprpicker.nix
    ./iannix.nix
    ./kitty.nix
    ./libreoffice.nix
    ./masterpdfeditor.nix
    ./mate-calc.nix
    ./obsidian.nix
    ./opensnitch-ui.nix
    ./openshot.nix
    ./pinta.nix
    ./pulsemixer.nix
    ./rofi.nix
    ./seahorse.nix
    ./smplayer.nix
    ./szyszka.nix
    ./thunar.nix
    ./veracrypt.nix
    ./virt-manager.nix
    ./vscode.nix
    ./zoom.nix
  ];
}
