{lib, ...}:

with lib;
{
  imports = [
    ./android-tools.nix
    ./bat.nix
    ./bash.nix
    ./btop.nix
    ./comma.nix
    ./development.nix
    ./direnv.nix
    ./duf.nix
    ./dust.nix
    ./encfs.nix
    ./file-compression.nix
    ./fish.nix
    ./fzf.nix
    ./git.nix
    ./gnupg.nix
    ./helix
    ./hugo.nix
    ./htop.nix
    ./jq.nix
    ./less.nix
    ./liquidprompt.nix
    ./lsd.nix
    ./mp3gain.nix
    ./mtr.nix
    ./ncdu.nix
    ./neofetch.nix
    ./neovim
    ./nix-developmenttools.nix
    ./nmap.nix
    ./python.nix
    ./ranger.nix
    ./ripgrep.nix
    ./secrets.nix
    ./shfmt.nix
    ./shellcheck.nix
    ./spotify.nix
    ./timewarrior.nix
    ./wget.nix
    ./xdg-ninja.nix
    ./xmlstarlet.nix
    ./yq.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zenity.nix
    ./zoxide.nix
  ];
}
